openapi: 3.0.0
info:
  title: WhaTap Projects API
  version: 1.0.0
  description: API to access information about projects in WhaTap.
servers:
  - url: 'https://api.whatap.io'
paths:
  /open/api/json/projects:
    get:
      summary: Retrieves a list of projects
      operationId: getProjects
      tags:
        - Project
      parameters:
        - name: x-whatap-token
          in: header
          required: true
          schema:
            type: string
          description: API token for authentication
      responses:
        '200':
          description: Successful retrieval of project list
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        groupName:
                          type: string
                        projectCode:
                          type: integer
                        projectName:
                          type: string
                        createTime:
                          type: string
                          format: date-time
                        lastUpdatedTime:
                          type: string
                          format: date-time
                        status:
                          type: string
                        productType:
                          type: string
                        platform:
                          type: string
                        gatewayName:
                          type: string
                        apiToken:
                          type: string
                  accountEmail:
                    type: string
                  total:
                    type: integer
                example:
                  data:
                    - groupName: ""
                      projectCode: 35
                      projectName: "APM_TEST2"
                      createTime: "2018-10-19T07:17:03.774"
                      status: "subscribe"
                      productType: "APM"
                      platform: "JAVA"
                      gatewayName: "LOCAL"
                      apiToken: "5**********************R"
                  accountEmail: "xxx@whatap.io"
                  total: 6
